language: node_js
node_js:
  - 10.8

install:
  - npm install 
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - npm ci
    - npm run cy:verify
    
before_script:
  - npm start &

script:
  - npm run newmanApiTest
  - npm run cy:run
  - kill $(jobs -p) || true
