language: node_js
node_js:
  - 10.8
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
before_script:
  - npm start &
script:
  - npm run newmanApiTest
  - $(npm bin)/cypress run --record
  - kill $(jobs -p) || true
